package com.games.sega.genesis;

/* This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int audioStretchValues = 2130771968;
        public static final int buttonNumberArray = 2130771969;
        public static final int buttonNumberValues = 2130771970;
        public static final int frameSkipValues = 2130771971;
        public static final int hardwareFilterArray = 2130771972;
        public static final int hardwareFilterValues = 2130771973;
        public static final int listArray = 2130771974;
        public static final int listValues = 2130771975;
    }

    public static final class attr {
        public static final int adSize = 2130837504;
        public static final int adSizes = 2130837505;
        public static final int adUnitId = 2130837506;
        public static final int coordinatorLayoutStyle = 2130837507;
        public static final int font = 2130837508;
        public static final int fontProviderAuthority = 2130837509;
        public static final int fontProviderCerts = 2130837510;
        public static final int fontProviderFetchStrategy = 2130837511;
        public static final int fontProviderFetchTimeout = 2130837512;
        public static final int fontProviderPackage = 2130837513;
        public static final int fontProviderQuery = 2130837514;
        public static final int fontStyle = 2130837515;
        public static final int fontWeight = 2130837516;
        public static final int keylines = 2130837517;
        public static final int layout_anchor = 2130837518;
        public static final int layout_anchorGravity = 2130837519;
        public static final int layout_behavior = 2130837520;
        public static final int layout_dodgeInsetEdges = 2130837521;
        public static final int layout_insetEdge = 2130837522;
        public static final int layout_keyline = 2130837523;
        public static final int maxValue = 2130837524;
        public static final int minValue = 2130837525;
        public static final int statusBarBackground = 2130837526;
    }

    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 2130903040;
    }

    public static final class color {
        public static final int black = 2130968576;
        public static final int gray_color = 2130968577;
        public static final int notification_action_color_filter = 2130968578;
        public static final int notification_icon_bg_color = 2130968579;
        public static final int notification_material_background_media_default_color = 2130968580;
        public static final int orange = 2130968581;
        public static final int primary_text_default_material_dark = 2130968582;
        public static final int ripple_material_light = 2130968583;
        public static final int secondary_text_default_material_dark = 2130968584;
        public static final int secondary_text_default_material_light = 2130968585;
        public static final int white_color = 2130968586;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 2131034112;
        public static final int compat_button_inset_vertical_material = 2131034113;
        public static final int compat_button_padding_horizontal_material = 2131034114;
        public static final int compat_button_padding_vertical_material = 2131034115;
        public static final int compat_control_corner_material = 2131034116;
        public static final int notification_action_icon_size = 2131034117;
        public static final int notification_action_text_size = 2131034118;
        public static final int notification_big_circle_margin = 2131034119;
        public static final int notification_content_margin_start = 2131034120;
        public static final int notification_large_icon_height = 2131034121;
        public static final int notification_large_icon_width = 2131034122;
        public static final int notification_main_column_padding_top = 2131034123;
        public static final int notification_media_narrow_margin = 2131034124;
        public static final int notification_right_icon_size = 2131034125;
        public static final int notification_right_side_padding_top = 2131034126;
        public static final int notification_small_icon_background_padding = 2131034127;
        public static final int notification_small_icon_size_as_large = 2131034128;
        public static final int notification_subtext_size = 2131034129;
        public static final int notification_top_pad = 2131034130;
        public static final int notification_top_pad_large_text = 2131034131;
    }

    public static final class drawable {
        public static final int icon = 2131099648;
        public static final int notification_action_background = 2131099649;
        public static final int notification_bg = 2131099650;
        public static final int notification_bg_low = 2131099651;
        public static final int notification_bg_low_normal = 2131099652;
        public static final int notification_bg_low_pressed = 2131099653;
        public static final int notification_bg_normal = 2131099654;
        public static final int notification_bg_normal_pressed = 2131099655;
        public static final int notification_icon_background = 2131099656;
        public static final int notification_template_icon_bg = 2131099657;
        public static final int notification_template_icon_low_bg = 2131099658;
        public static final int notification_tile_bg = 2131099659;
        public static final int notify_panel_notification_icon_bg = 2131099660;
    }

    public static final class id {
        public static final int TextView01 = 2131165184;
        public static final int TextView02 = 2131165185;
        public static final int action0 = 2131165186;
        public static final int action_container = 2131165187;
        public static final int action_divider = 2131165188;
        public static final int action_image = 2131165189;
        public static final int action_text = 2131165190;
        public static final int actions = 2131165191;
        public static final int adPref1 = 2131165192;
        public static final int adPref2 = 2131165193;
        public static final int adView = 2131165194;
        public static final int ad_layout = 2131165195;
        public static final int all = 2131165196;
        public static final int async = 2131165197;
        public static final int blocking = 2131165198;
        public static final int bottom = 2131165199;
        public static final int buttonBack = 2131165200;
        public static final int buttonExit = 2131165201;
        public static final int buttonHelp = 2131165202;
        public static final int buttonLoadRom = 2131165203;
        public static final int buttonResume = 2131165204;
        public static final int buttonSettings = 2131165205;
        public static final int cancel_action = 2131165206;
        public static final int center = 2131165207;
        public static final int center_horizontal = 2131165208;
        public static final int center_vertical = 2131165209;
        public static final int chronometer = 2131165210;
        public static final int clip_horizontal = 2131165211;
        public static final int clip_vertical = 2131165212;
        public static final int current_value = 2131165213;
        public static final int end = 2131165214;
        public static final int end_padder = 2131165215;
        public static final int fileChooserSubmit = 2131165216;
        public static final int fileChooserView = 2131165217;
        public static final int fill = 2131165218;
        public static final int fill_horizontal = 2131165219;
        public static final int fill_vertical = 2131165220;
        public static final int forever = 2131165221;
        public static final int icon = 2131165222;
        public static final int icon_group = 2131165223;
        public static final int info = 2131165224;
        public static final int italic = 2131165225;
        public static final int left = 2131165226;
        public static final int line1 = 2131165227;
        public static final int line3 = 2131165228;
        public static final int max_value = 2131165229;
        public static final int media_actions = 2131165230;
        public static final int menuActions = 2131165231;
        public static final int menuExit = 2131165232;
        public static final int menuHide = 2131165233;
        public static final int menuLoadROM = 2131165234;
        public static final int menuLoadState = 2131165235;
        public static final int menuResetGame = 2131165236;
        public static final int menuSaveState = 2131165237;
        public static final int menuSelectState = 2131165238;
        public static final int menuSettings = 2131165239;
        public static final int menuState0 = 2131165240;
        public static final int menuState1 = 2131165241;
        public static final int menuState10 = 2131165242;
        public static final int menuState2 = 2131165243;
        public static final int menuState3 = 2131165244;
        public static final int menuState4 = 2131165245;
        public static final int menuState5 = 2131165246;
        public static final int menuState6 = 2131165247;
        public static final int menuState7 = 2131165248;
        public static final int menuState8 = 2131165249;
        public static final int menuState9 = 2131165250;
        public static final int min_value = 2131165251;
        public static final int none = 2131165252;
        public static final int normal = 2131165253;
        public static final int notification_background = 2131165254;
        public static final int notification_main_column = 2131165255;
        public static final int notification_main_column_container = 2131165256;
        public static final int right = 2131165257;
        public static final int right_icon = 2131165258;
        public static final int right_side = 2131165259;
        public static final int seek_bar = 2131165260;
        public static final int start = 2131165261;
        public static final int status_bar_latest_event_content = 2131165262;
        public static final int tag_transition_group = 2131165263;
        public static final int text = 2131165264;
        public static final int text2 = 2131165265;
        public static final int textView1 = 2131165266;
        public static final int textView2 = 2131165267;
        public static final int textViewAnswer1 = 2131165268;
        public static final int textViewAnswer2 = 2131165269;
        public static final int textViewAnswer3 = 2131165270;
        public static final int textViewAnswer4part1 = 2131165271;
        public static final int textViewAnswer4part2 = 2131165272;
        public static final int textViewAnswer4part3 = 2131165273;
        public static final int textViewAnswer4part4 = 2131165274;
        public static final int textViewAnswer5part1 = 2131165275;
        public static final int textViewAnswer5part2 = 2131165276;
        public static final int textViewAnswer6part1 = 2131165277;
        public static final int textViewAnswer6part2 = 2131165278;
        public static final int textViewAnswer7part1 = 2131165279;
        public static final int textViewAnswer7part2 = 2131165280;
        public static final int textViewAnswer7part3 = 2131165281;
        public static final int textViewCopyright = 2131165282;
        public static final int textViewQuestion1 = 2131165283;
        public static final int textViewQuestion2 = 2131165284;
        public static final int textViewQuestion3 = 2131165285;
        public static final int textViewQuestion4 = 2131165286;
        public static final int textViewQuestion5 = 2131165287;
        public static final int textViewQuestion6 = 2131165288;
        public static final int textViewQuestion7 = 2131165289;
        public static final int textViewTitle = 2131165290;
        public static final int textViewVersion = 2131165291;
        public static final int time = 2131165292;
        public static final int title = 2131165293;
        public static final int top = 2131165294;
        public static final int txtExample = 2131165295;
    }

    public static final class integer {
        public static final int cancel_button_image_alpha = 2131230720;
        public static final int google_play_services_version = 2131230721;
        public static final int status_bar_notification_info_maxnum = 2131230722;
    }

    public static final class layout {
        public static final int ad_layout = 2131296256;
        public static final int custom_key_view = 2131296257;
        public static final int dialog_slider = 2131296258;
        public static final int file_choose = 2131296259;
        public static final int file_view = 2131296260;
        public static final int help = 2131296261;
        public static final int main = 2131296262;
        public static final int notification_action = 2131296263;
        public static final int notification_action_tombstone = 2131296264;
        public static final int notification_media_action = 2131296265;
        public static final int notification_media_cancel_action = 2131296266;
        public static final int notification_template_big_media = 2131296267;
        public static final int notification_template_big_media_custom = 2131296268;
        public static final int notification_template_big_media_narrow = 2131296269;
        public static final int notification_template_big_media_narrow_custom = 2131296270;
        public static final int notification_template_custom_big = 2131296271;
        public static final int notification_template_icon_group = 2131296272;
        public static final int notification_template_lines_media = 2131296273;
        public static final int notification_template_media = 2131296274;
        public static final int notification_template_media_custom = 2131296275;
        public static final int notification_template_part_chronometer = 2131296276;
        public static final int notification_template_part_time = 2131296277;
        public static final int settings = 2131296278;
    }

    public static final class menu {
        public static final int emulator = 2131361792;
        public static final int keyboard_config_menu = 2131361793;
    }

    public static final class string {
        public static final int Copyright = 2131427328;
        public static final int app_description = 2131427329;
        public static final int app_name = 2131427330;
        public static final int app_version = 2131427331;
        public static final int buttonExit = 2131427332;
        public static final int buttonOk = 2131427333;
        public static final int buttonRetry = 2131427334;
        public static final int buttonSubmit = 2131427335;
        public static final int common_google_play_services_unknown_issue = 2131427336;
        public static final int default_web_client_id = 2131427337;
        public static final int fileChooseCurrentDirectory = 2131427338;
        public static final int fileChooseFileClicked = 2131427339;
        public static final int fileChooseFileSize = 2131427340;
        public static final int fileChooseFolder = 2131427341;
        public static final int fileChooseNoRomSelected = 2131427342;
        public static final int fileChooseParentDirectory = 2131427343;
        public static final int fileChooseSelected = 2131427344;
        public static final int firebase_database_url = 2131427345;
        public static final int gcm_defaultSenderId = 2131427346;
        public static final int google_api_key = 2131427347;
        public static final int google_app_id = 2131427348;
        public static final int google_crash_reporting_api_key = 2131427349;
        public static final int google_storage_bucket = 2131427350;
        public static final int helpAnswer1 = 2131427351;
        public static final int helpAnswer2 = 2131427352;
        public static final int helpAnswer3 = 2131427353;
        public static final int helpAnswer4part1 = 2131427354;
        public static final int helpAnswer4part2 = 2131427355;
        public static final int helpAnswer4part3 = 2131427356;
        public static final int helpAnswer4part4 = 2131427357;
        public static final int helpAnswer5part1 = 2131427358;
        public static final int helpAnswer5part2 = 2131427359;
        public static final int helpAnswer6part1 = 2131427360;
        public static final int helpAnswer6part2 = 2131427361;
        public static final int helpAnswer7part1 = 2131427362;
        public static final int helpAnswer7part2 = 2131427363;
        public static final int helpAnswer7part3 = 2131427364;
        public static final int helpBack = 2131427365;
        public static final int helpQuestion1 = 2131427366;
        public static final int helpQuestion2 = 2131427367;
        public static final int helpQuestion3 = 2131427368;
        public static final int helpQuestion4 = 2131427369;
        public static final int helpQuestion5 = 2131427370;
        public static final int helpQuestion6 = 2131427371;
        public static final int helpQuestion7 = 2131427372;
        public static final int helpTitle = 2131427373;
        public static final int menuActions = 2131427374;
        public static final int menuHelp = 2131427375;
        public static final int menuHide = 2131427376;
        public static final int menuLoadRom = 2131427377;
        public static final int menuLoadState = 2131427378;
        public static final int menuResetGame = 2131427379;
        public static final int menuResume = 2131427380;
        public static final int menuResumeNoRomLoaded = 2131427381;
        public static final int menuSaveState = 2131427382;
        public static final int menuSelectState = 2131427383;
        public static final int menuSettings = 2131427384;
        public static final int menuState0 = 2131427385;
        public static final int menuState1 = 2131427386;
        public static final int menuState10 = 2131427387;
        public static final int menuState2 = 2131427388;
        public static final int menuState3 = 2131427389;
        public static final int menuState4 = 2131427390;
        public static final int menuState5 = 2131427391;
        public static final int menuState6 = 2131427392;
        public static final int menuState7 = 2131427393;
        public static final int menuState8 = 2131427394;
        public static final int menuState9 = 2131427395;
        public static final int messageExternalStorageSummary = 2131427396;
        public static final int messageExternalStorageTitle = 2131427397;
        public static final int package_name = 2131427398;
        public static final int project_id = 2131427399;
        public static final int s1 = 2131427400;
        public static final int s2 = 2131427401;
        public static final int s3 = 2131427402;
        public static final int s4 = 2131427403;
        public static final int s5 = 2131427404;
        public static final int s6 = 2131427405;
        public static final int s7 = 2131427406;
        public static final int settingAudioStretch = 2131427407;
        public static final int settingAutosave = 2131427408;
        public static final int settingAutosaveSummary = 2131427409;
        public static final int settingCategoryAudio = 2131427410;
        public static final int settingCategoryDirectories = 2131427411;
        public static final int settingCategoryEmulation = 2131427412;
        public static final int settingCategoryGraphics = 2131427413;
        public static final int settingCategoryInput = 2131427414;
        public static final int settingConfigureKeyInput = 2131427415;
        public static final int settingConfigureKeyInputLine = 2131427416;
        public static final int settingConfigureKeyInputSummary = 2131427417;
        public static final int settingConfigureTouchAlert0 = 2131427418;
        public static final int settingConfigureTouchAlert1 = 2131427419;
        public static final int settingConfigureTouchAlert2 = 2131427420;
        public static final int settingConfigureTouchAlert3 = 2131427421;
        public static final int settingConfigureTouchAlertTitle = 2131427422;
        public static final int settingConfigureTouchInput = 2131427423;
        public static final int settingConfigureTouchInputSummary = 2131427424;
        public static final int settingConfigureTouchLeaveResizeMode = 2131427425;
        public static final int settingEnableAudio = 2131427426;
        public static final int settingFrameskip = 2131427427;
        public static final int settingGameGenieCantAutoload = 2131427428;
        public static final int settingGameGenieNotFoundSummary = 2131427429;
        public static final int settingGameGenieNotFoundTitle = 2131427430;
        public static final int settingHardwareFiltering = 2131427431;
        public static final int settingHardwareFilteringLinearInterpolation = 2131427432;
        public static final int settingHardwareFilteringPointFiltering = 2131427433;
        public static final int settingMaintainAspectRatio = 2131427434;
        public static final int settingResetInput = 2131427435;
        public static final int settingResetInputSummary = 2131427436;
        public static final int settingSelectRomDir = 2131427437;
        public static final int settingSelectRomDirSummary = 2131427438;
        public static final int settingSelectSramDir = 2131427439;
        public static final int settingSelectSramDirSummary = 2131427440;
        public static final int settingSelectStateDir = 2131427441;
        public static final int settingSelectStateDirSummary = 2131427442;
        public static final int settingSelectTempDir = 2131427443;
        public static final int settingSelectTempDirSummary = 2131427444;
        public static final int settingSetButtonNumber = 2131427445;
        public static final int settingSetButtonNumber3ButtonPad = 2131427446;
        public static final int settingSetButtonNumber6ButtonPad = 2131427447;
        public static final int settingShowTouchInput = 2131427448;
        public static final int settingSoundSampleRate = 2131427449;
        public static final int status_bar_notification_info_overflow = 2131427450;
    }

    public static final class style {
        public static final int AppTheme = 2131492864;
        public static final int TextAppearance_Compat_Notification = 2131492865;
        public static final int TextAppearance_Compat_Notification_Info = 2131492866;
        public static final int TextAppearance_Compat_Notification_Info_Media = 2131492867;
        public static final int TextAppearance_Compat_Notification_Line2 = 2131492868;
        public static final int TextAppearance_Compat_Notification_Line2_Media = 2131492869;
        public static final int TextAppearance_Compat_Notification_Media = 2131492870;
        public static final int TextAppearance_Compat_Notification_Time = 2131492871;
        public static final int TextAppearance_Compat_Notification_Time_Media = 2131492872;
        public static final int TextAppearance_Compat_Notification_Title = 2131492873;
        public static final int TextAppearance_Compat_Notification_Title_Media = 2131492874;
        public static final int Theme_IAPTheme = 2131492875;
        public static final int Widget_Compat_NotificationActionContainer = 2131492876;
        public static final int Widget_Compat_NotificationActionText = 2131492877;
        public static final int Widget_Support_CoordinatorLayout = 2131492878;
        public static final int emuTheme = 2131492879;
    }

}
